### ISSUE TITLE
Too large whiteboard files may cause sync to stop

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/whiteboard#106]
Still to reproduce but @grnd-alt mentioned this happened while working on the embeddings and there was an issue causing tons of elements being added.

> websocket 1009 error

We should try to come up with larger files with 1k 10k 100k elements and test that

**Comment by juliushaertl** [comment]
@grnd-alt Could you check that again to see if there is any way to reproduce and document them in here?

**Comment by grnd-alt** [comment]
@juliushaertl I was not able to directly reproduce. I tried adding a lot of elements programmatically but I did not get the same websocket error, the ui rather slowed down a lot before the websocket message reached it's limit. I think we can Ignore this issue for now and handle it in case the images from https://github.com/nextcloud/whiteboard/issues/56#issuecomment-2316834546 are to big.
