### ISSUE TITLE
Rename App to NC-whiteboard?

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/whiteboard#162]
Hey there,

seemingly this is the one app that was heavily featured on the NC Conference presentation of NC30/Hub 9.
Though it was presented as "Nextcloud whiteboard". 
As we do have some more apps being named "whiteboard" I think it would be nice if we/you would rename this app to "NC-whiteboard". (or similar) 
Just to show ppl that this is the one whiteboard that comes "nativly" with NC and will be maintained as well as NC itself.
And to make a difference to all other "whiteboard"-apps.

What do you think?

**Comment by AndyScherzinger** [comment]
I think quite the opposite is the to be the case or direction. The current name fits the general naming scheme. We also don't call Deck nc-deck or call Tables nc-tables.

The app is currently called Whiteboard and so it the app ID in the app store and also the repo name here under the umbrella Github organization.

However just my opinion but matches our general naming schema of going for the matching name for the apps functionality and not prefixing all app names.

@jancborchardt

**Comment by juliushaertl** [comment]
I'd generally agree with Andy that we rather use just the main app name anywhere. Let me close this but would still monitor to see if @jospoortvliet or @jancborchardt have any further to add.
