### ISSUE TITLE
readme.md: prerequisites compiling websocket-server

### ISSUE THREAD

**Issue by jooooaah** [nextcloud/whiteboard#163]
Small hint for compiling websocket-server: minimum nodejs version is  v16.9.0 because hasOwn is only available since then. Didn't do any pr because perhaps it's more necessary?

**Comment by juliushaertl** [comment]
Seems I actually did this in https://github.com/nextcloud/whiteboard/commit/92e0cb593cef304630985b395215997fd8daf30a
