### ISSUE TITLE
NC App Configuration doesnt work

### ISSUE THREAD

**Issue by egelhaus** [nextcloud/whiteboard#164]
When I try to connect my NC with the NC Whiteboard, it gets me this Error on the Config GUI (NC):
`Failed to verify the connection: timeout`

My docker-compose.yml:
`version: '3.7'
services:
  nextcloud-whiteboard-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - NEXTCLOUD_URL=http://192.168.178.189:11000
      - JWT_SECRET_KEY=my_jwt_secret`
      
      My NC Commands that have been executed:
`sudo -u www-data php occ config:app:set whiteboard collabBackendUrl --value="http://192.168.178.189:3002"`
`sudo -u www-data php occ config:app:set whiteboard jwt_secret_key --value="my_jwt_secret"`

Note:
Im running an AIO NC Setup behind an Nginx Proxy Manager, i also tried both NEXTCLOUD_URL and collabBackendUrl behind the NGM.

**Comment by egelhaus** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
Can you share how you configured your reverse proxy?

**Comment by egelhaus** [comment]
@juliushaertl I Cant rn, bcs im Not Home, but when im Home , I will Send you my Config, but Its in the WebUI of Nginx Proxy Manager. And Even when I try to Not Reverse Proxy it over the local IP Address, it doesnt work.

**Comment by juliushaertl** [comment]
Ok, in that case the public domain name should be configured as collabBackendUrl not the internal IP/port. Could you give that a try?

**Comment by egelhaus** [comment]
I did that too. It didnt work

**Comment by juliushaertl** [comment]
Can you open that URL in the browser and see if you get a message like "Excalidraw collaboration server is up :)"

**Comment by egelhaus** [comment]
yup:

**Comment by egelhaus** [comment]
Excalidraw collaboration server is up :)

**Comment by egelhaus** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
All right, can you tell what happens if you create a new .whiteboard file in the files app? Is it downloaded or is the opening and you see any error?

**Comment by egelhaus** [comment]
one sec

**Comment by egelhaus** [comment]
![image](https://github.com/user-attachments/assets/068520e8-944b-430f-9f05-eaa8433e05d2)
It ends with an Error.
Idk if thats important, but i did --skip-domain-validation=true
@juliushaertl

**Comment by egelhaus** [comment]
@juliushaertl ?

**Comment by rawtaz** [comment]
@egelhaus This is not a personal support chat. Please understand that @juliushaertl works during work hours and will reply when he can. You have to be patient :)

**Comment by BADGRRL666** [comment]
Same issue here, no luck with nginx proxy manager. Server and Nextcloud instance are on the same subnet.

I tried running it on the same host with both Docker and NPM but seems to be just as broken.

**Comment by LinoSchmidt** [comment]
Worked for me by adding the reverse proxy config into the advanced section of my Nextcloud reverse proxy config and then putting the address of my Nextcloud Server into `collabBackendUrl`.

Also replaced `/whiteboard/` with `/socket.io/`

![Screenshot 2024-09-18 174749](https://github.com/user-attachments/assets/6f2063b9-e5ea-4a13-bf64-e7afadf22f28)

**Comment by egelhaus** [comment]
@LinoSchmidt Could you please provide your collabBackendURl with example.com and provide your Advanced Config please?

**Comment by LinoSchmidt** [comment]
collabBackendURl should look like `https://cloud.example.com`

Advanced config of my reverse proxy for Nextcloud:
```
location /socket.io/ {
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Host $host;
	
	proxy_pass http://$server:3002;
	
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
}
```

`$server` should be the IP address of the whiteboard server.
For me, it's the same IP as my Nextcloud server because I run both on Docker, so I set it to `$server`.

**Comment by egelhaus** [comment]
@LinoSchmidt Thank you, but the Beta for AIO was just releseased, and i didnt saw it, im trying to install it now, if it doesnt work, ill try this one out. But Thank you.

**Comment by nerpdaderp** [comment]
I want to thank you from the very bottom of my grateful heart. I've spent the last 15 to 20 hours trying to get whiteboard to accept a URL without an error. Nginx configured with socket.io, the server ip:3002/, and the backed url with /whiteboard was the magical trifecta of mysterious powers that finally, after nearly losing every last remnant of hope, and no less then 5 fresh nextcloud installs, FINALLY!!!! gave me the green light. You've made my night and prompted this, my first comment ever expressed on any forum during the last decade of my general dabbling in linux and networking. Only you guys and maybe my wife will know the epic scale of the battle won tonight, a lifetime pinnacle of success and perseverance. It Literally would not have been possible without this singular conversation having taken place, recorded on the internet for the benefit of all. Go in peace my friends, and may the universe bless your existence and all your future endeavors.

**Comment by xenorites** [comment]
> collabBackendURl should look like `https://cloud.example.com`
> 
> Advanced config of my reverse proxy for Nextcloud:
> 
> ```
> location /socket.io/ {
> 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 	proxy_set_header Host $host;
> 	
> 	proxy_pass http://$server:3002;
> 	
> 	proxy_http_version 1.1;
> 	proxy_set_header Upgrade $http_upgrade;
> 	proxy_set_header Connection "upgrade";
> }
> ```
> 
> `$server` should be the IP address of the whiteboard server. For me, it's the same IP as my Nextcloud server because I run both on Docker, so I set it to `$server`.

Can confirm, just spent hours fighting with this, and you *must* pass the `/socket.io` path through specifically for it to connect.

To wit, the instructions on the wiki are just wrong for nginx; if you wanted the server at `https://nextcloud.domain.com/whiteboard` you must tell nginx the path to be proxied is `/whiteboard/socket.io`.
