### ISSUE TITLE
Can't activate whiteboard app

### ISSUE THREAD

**Issue by LabanPheidias** [nextcloud/whiteboard#176]
I have a problem with activating the app. 

I run nextcloud 28.10 with php 8.0.30 on RHEL 9.4

GET","url":"/index.php/apps/files/","message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/local_disk/hive/site/apps/whiteboard/lib/Service/ConfigService.php' line 25","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0","version":"28.0.10.1","exception":{"Exception":"Exception","Message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/local_disk/hive/site/apps/whiteboard/lib/Service/ConfigService.php' line 25","Code":0,"Trace":[{"file":"/local_disk/hive/site/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/local_disk/hive/site/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/local_disk/hive/site/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/local_disk/hive/site/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/local_disk/hive/site/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString()","Code":0,"Trace":[{"file":"/local_disk/hive/site/apps/whiteboard/lib/Listener/LoadViewerListener.php","line":38,"function":"getCollabBackendUrl","class":"OCA\\Whiteboard\\Service\\ConfigService","type":"->"},{"file":"/local_disk/hive/site/lib/private/EventDispatcher/ServiceEventListener.php","line":86,"function":"handle","class":"OCA\\Whiteboard\\Listener\\LoadViewerListener","type":"->"},{"file":"/local_disk/hive/site/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":230,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/local_disk/hive/site/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/local_disk/hive/site/lib/private/EventDispatcher/EventDispatcher.php","line":94,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/local_disk/hive/site/lib/private/EventDispatcher/EventDispatcher.php","line":106,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/local_disk/hive/site/apps/files/lib/Controller/ViewController.php","line":285,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/local_disk/hive/site/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/local_disk/hive/site/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/local_disk/hive/site/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/local_disk/hive/site/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/local_disk/hive/site/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/local_disk/hive/site/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/local_disk/hive/site/apps/whiteboard/lib/Service/ConfigService.php","Line":25},"message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/local_disk/hive/site/apps/whiteboard/lib/Service/ConfigService.php' line 25","exception":{},"CustomMessage":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/local_disk/hive/site/apps/whiteboard/lib/Service/ConfigService.php' line 25"}}

**Comment by R053NR07** [comment]
I'm getting the same error on NC28.

**Comment by natrius** [comment]
Nextcloud 28.0.10 on Ubuntu 22.04.4 LTS, baremetal, with nginx. When trying to download in nextcloud apps it shows "Error: App could not get activated because it makes the server unstable.". 

Whiteboard 1.0.2

```
{"reqId":"N1tiw6Z030vNyaXjFst5","level":3,"time":"2024-09-25T15:04:24+02:00","remoteAddr":"IPADRESS","user":"USERNAME","app":"index","method":"GET","url":"/apps/files/","message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/var/www/nextcloud/apps/whiteboard/lib/Service/ConfigService.php' line 25","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0","version":"28.0.10.1","exception":{"Exception":"Exception","Message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/var/www/nextcloud/apps/whiteboard/lib/Service/ConfigService.php' line 25","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString()","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/whiteboard/lib/Listener/LoadViewerListener.php","line":38,"function":"getCollabBackendUrl","class":"OCA\\Whiteboard\\Service\\ConfigService","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":86,"function":"handle","class":"OCA\\Whiteboard\\Listener\\LoadViewerListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":230,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":94,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":106,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/files/lib/Controller/ViewController.php","line":285,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"index","class":"OCA\\Files\\Controller\\ViewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/apps/whiteboard/lib/Service/ConfigService.php","Line":25},"message":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/var/www/nextcloud/apps/whiteboard/lib/Service/ConfigService.php' line 25","exception":[],"CustomMessage":"Call to undefined method OC\\AppFramework\\Services\\AppConfig::getAppValueString() in file '/var/www/nextcloud/apps/whiteboard/lib/Service/ConfigService.php' line 25"},"id":"66f40aa84f935"}
```

**Comment by LabanPheidias** [comment]
I upgraded to v29.0.7 without changing anything, and the whiteboard app can now be started.

**Comment by R053NR07** [comment]
> I upgraded to v29.0.7 without changing anything, and the whiteboard app can now be started.

For us this is not a solution since NC29 will break bbb Integration :/

**Comment by idominiki** [comment]
I've the same problem with Whiteboard App 1.0.4.

NC28.0.7 is installed through Univention App Center, Whiteboard Server is hosted via docker-compose on external server and is available through https public domain.

![Image](https://github.com/user-attachments/assets/c12759ef-7b9a-4e9d-8960-ef405ffabf6d)
![Image](https://github.com/user-attachments/assets/b756e22e-55eb-4f3e-8301-e1b5c27dbfb6)
