### ISSUE TITLE
Docker Compose's AIO NC downloads file instead of opening

### ISSUE THREAD

**Issue by AverageDood** [nextcloud/whiteboard#182]
I'm using NC through a Docker Compose file, as well as Whiteboard, both of them behind Nginx Proxy Manager entries, with HTTPS and functioning properly. The configuration's all good, the connection is green, both servers are reachable and can see each other, yada yada. But when I create a file on NC and I try to open it, it instead just downloads.

I've opened a bash on the nextcloud container to check the mimetype thing the readme talks about when this happens, but the "mimetypealiases.json" file doesn't exist, neither does the "mimetypemapping.js". "mimetypemapping.dist.js" does exist, although no metions or entries about "whiteboard" or "wbr" are there, and even if they were, I read on NC's docs that the dist files are not for us to touch.

So what do I pull to fix this?

**Comment by juliushaertl** [comment]
Which Nextcloud version are you using? Can you verify that the shipped file in `resources/config/mimetypealiases.dist.json` has the following entry?

```
	"application/vnd.excalidraw+json": "whiteboard",
```

**Comment by AverageDood** [comment]
Sorry for the delay, it's been a busy time.

Nextcloud version is 29.0.4, Hub 8, and the entry does not exist in the mimetypealiases file. Not a trace of whiteboard or excalidraw anywhere

**Comment by AverageDood** [comment]
Bad news: trying to regain access to the AIO interface, I broke my Nextcloud. No biggie, nothing important was lost, got access to the data folder and saved everything.

Good news: i installed Whiteboard from the AIO interface when reinstalling Nextcloud and can confirm it just works. I only need to re-make 2 accounts and re-upload my stuff, the other guy had nothing uploaded so, as said: nothing was lost
