### ISSUE TITLE
Incorrect documentation on reverse proxy

### ISSUE THREAD

**Issue by lumintulogic-admin** [nextcloud/whiteboard#183]
- For **Apache**, it was written using ws as the protocol, it should be http:

```
ProxyPass /whiteboard http://localhost:3002/
RewriteEngine on
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/?whiteboard/(.*) "http://localhost:3002/$1" [P,L]
```

- And for **Nginx**, it was missing a forward slash at the end of the proxy_pass directive, it should be:

```
location /whiteboard/ {
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Host $host;	
	proxy_pass http://localhost:3002/;	
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
}
```

**Comment by kinimodmeyer** [comment]
Are you sure it should be http? With ws:// the admin-page can not connect to it.

**Comment by lumintulogic-admin** [comment]
> Are you sure it should be http? With http:// instead of ws:// the admin-page can not connect to it.

I tried mine with nginx config as written in my correction above, and the backend url used in the admin page is the nextcloud instance's URL (using https) concatenated with "/whiteboard"
![Capture](https://github.com/user-attachments/assets/e3b2c33e-5a31-4e35-a81e-8d287256603c)

**Comment by ralfi** [comment]
For Apache you can also rewrite everything if you have a sub-domain with LE Cert like this:


![Auswahl_005](https://github.com/user-attachments/assets/91be3c56-7295-40bf-b15b-1df331234d94)

**Comment by juliushaertl** [comment]
> Are you sure it should be http? With http:// instead of ws:// the admin-page can not connect to it.

Yes, I also double checked and the config for apache and nginx work fine for me as they are stated in the readme. Can you describe what issues you experience with those?
