### ISSUE TITLE
Public share link tries to open whiteboard

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/whiteboard#191]
On c.n.c.:
- create a public link share
- open it
--> see that it opens whiteboard

![image](https://github.com/user-attachments/assets/06a1b348-ad62-4874-bf26-6d3697db2271)

**Comment by punkyard** [comment]
i confirm the issue
AiO 960

**Comment by szaimen** [comment]
Looks like this might have fixed it? https://github.com/nextcloud/whiteboard/pull/201

**Comment by grnd-alt** [comment]
fixed by #201
