### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by sunjam** [nextcloud/whiteboard#199]
Excalidraw does not yet support arm64 architecture.
- https://github.com/excalidraw/excalidraw/issues/6597

A number of pull requests are attempting to address this
- https://github.com/excalidraw/excalidraw/pull/8250
- https://github.com/excalidraw/excalidraw/pull/7806
- https://github.com/excalidraw/excalidraw/pull/6989 
- https://github.com/excalidraw/excalidraw/pull/6796 
- https://github.com/excalidraw/excalidraw/pull/3937

**Comment by szaimen** [comment]
Hi, as far as I know does the whiteboard app indeed support arm64 as we build our own container images: https://github.com/nextcloud-releases/whiteboard/pkgs/container/whiteboard

**Comment by sunjam** [comment]
Is that true of just AIO as opposed to all other versions of Nextcloud, such as Snap, etc?

**Comment by szaimen** [comment]
Yes, everyone can install this container which is built for amd64 and arm64 and is the backend for the whiteboard app.

**Comment by sunjam** [comment]
Okay, then I'll close this issue if the limitations of regular Excalidraw builds do not apply on Nextcloud.  Thanks.
