### ISSUE TITLE
Dark mode: Everything white, only buttons and highlighted items dark (but no contrast to text)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/whiteboard#65]
Just tested on our daily instance, with dark mode it looks like this:

![image](https://github.com/nextcloud/whiteboard/assets/925062/4c9c858d-ed15-4e9d-97f5-738d1fbb6e13)

It seems Excalidraw does have a dark mode, and some docs are here if we need extra: https://docs.excalidraw.com/docs/@excalidraw/excalidraw/customizing-styles

Also, how do we deal with our templates? Is it possible to set the colors to something like "default background" and "default text" so it is properly displayed no matter if the person uses dark or light mode? @juliushaertl @nimishavijay 
(As first version it could also be fine if the templates are simply all forced light mode.)

**Comment by juliushaertl** [comment]
Initial attempt was in d13a1b6

With system dark mode it works fine:
<img width="1673" alt="Screenshot 2024-07-08 at 15 24 48" src="https://github.com/nextcloud/whiteboard/assets/3404133/5433c2d6-3e9d-44f8-88f2-01083b2a5036">



However it likely is something Andy noticed when the operating system and the nextcloud setting are different.

**Comment by jancborchardt** [comment]
@juliushaertl true, my operating system was set to light, and Nextcloud to dark. Somehow still appears though with operating system to dark and cookies cleared.

**Comment by AndyScherzinger** [comment]
@juliushaertl since we discussed this, for me it is the other way around:

* OS on dark theme
* Nc on light theme

result when opening a board:
<img width="1920" alt="2024-07-08 18_30_31-" src="https://github.com/nextcloud/whiteboard/assets/1315170/a251d072-13cd-422d-bc27-3d201681d8cd">
