### ISSUE TITLE
Re-evaluate file extension

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/whiteboard#66]
We should consider rather using something more generic by default like .whiteboard, supporting .excalidraw files still makes sense

**Comment by juliushaertl** [comment]
We used .whiteboard for the spacedeck integration app in the past so that could lead to old files still being around that we cannot open https://github.com/nextcloud/integration_whiteboard

@jancborchardt I also think hiding is not a good option for the file listing, we should not have special behavior there for some file types.

**Comment by jancborchardt** [comment]
> We used .whiteboard for the spacedeck integration app in the past so that could lead to old files still being around that we cannot open https://github.com/nextcloud/integration_whiteboard

I would say this is an OK drawback to take considering the age and state of that application (last release for Nextcloud 25), if we don’t want to hide the extension or there is no better other extension name.

`.whiteboard` makes most sense since that is the app name and it makes it obvious.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/46703
https://github.com/nextcloud/whiteboard/pull/80
