### ISSUE TITLE
Export image dialog issues

### ISSUE THREAD

**Issue by viktorix** [nextcloud/whiteboard#83]
Hey team, great job on the Whiteboard. I was testing it and noticed 3 issues with the exporting dialog:

1. The switches for options have some CSS issues.
2. Custom name field cannot be edited.
3. Embed scene question mark doesn't have a tooltip or link, doesn't do anything.

Screenshot:
![image](https://github.com/user-attachments/assets/4f8109b8-a0c5-40c7-8cd2-281e8ebefecb)

**Comment by juliushaertl** [comment]
Fixed with 0e33b62
