### ISSUE TITLE
Undo/Redo buttons missing title attributes

### ISSUE THREAD

**Issue by viktorix** [nextcloud/whiteboard#84]
Undo/Redo buttons use aria-label, but do not have title attributes. So hovering over them doesn't show a tooltip, you can't tell what they are unless you try using them.

For reference, Zoom buttons next to them do use titles.

Screenshot
![image](https://github.com/user-attachments/assets/66caf136-c9de-400a-b8d5-f2a637efb17f)

**Comment by juliushaertl** [comment]
@grnd-alt I think we can just have a small patch for the css so the tooltips from excalidraw have the right z-index after what we've looked at in our call last week
