### ISSUE TITLE
Save to dialog custom file name input not working

### ISSUE THREAD

**Issue by viktorix** [nextcloud/whiteboard#86]
When trying to save whiteboard as a file, the custom file name input doesn't work and is cut off:
![image](https://github.com/user-attachments/assets/9d8dca23-71e4-4057-8340-df0b48716b55)

**Comment by juliushaertl** [comment]
Need to check that, we had planned to hide that option completely

**Comment by juliushaertl** [comment]
Tested on main and we no longer show this:

<img width="340" alt="Screenshot 2024-07-25 at 11 55 15" src="https://github.com/user-attachments/assets/1e6440c0-766f-4313-bbe4-dff0481f2704">
