### ISSUE TITLE
Save as dialog offers .excalidraw file

### ISSUE THREAD

**Issue by viktorix** [nextcloud/whiteboard#87]
I noticed "Save as" dialog tries to save file as `.excalidraw` but NC download option offers `.whiteboard` file.

Based on #66 "Save as" should also offer .whiteboard file.

**Comment by juliushaertl** [comment]
Tested on main and we no longer show this:

<img width="340" alt="Screenshot 2024-07-25 at 11 55 15" src="https://github.com/user-attachments/assets/1e6440c0-766f-4313-bbe4-dff0481f2704">
