### ISSUE TITLE
Context menu empty keyboard shortcuts 

### ISSUE THREAD

**Issue by viktorix** [nextcloud/whiteboard#88]
In the context menu, actions without keyboard shortcut shouldn't show empty styling. 
![image](https://github.com/user-attachments/assets/966165b2-9583-4de3-bedd-c7bef27020cf)

**Comment by juliushaertl** [comment]
@grnd-alt Might be a good opportunity to check how to build the library locally, mabye come up with an upstream contribution to familiarize with the build process and how to link the library locally.

**Comment by juliushaertl** [comment]
Might also be just custom styles, upstream doesn't seem to have a box around the shortcuts
