### ISSUE TITLE
Whiteboard app store release

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/whiteboard#99]
- [x] Proper screenshots and add to info.xml
- [x] Set categories
- [x] Update description
- [x] Add to relevant app bundles
- [ ] Mark as featured (ping Jan?)
- [x] Notification to recommend app 
- [x] Documentation

**Comment by jancborchardt** [comment]
@juliushaertl let me know when the app store release is done and I can mark it as featured.

I would also remove the 2 existing comments since they are about the other previous whiteboard app which is completely different. Just noting it here for the record.

**Comment by juliushaertl** [comment]
@jancborchardt Pre-release is on the app store, so could be marked as featured. Did this as a dry run for the release process, final will be there for Saturday.

**Comment by jancborchardt** [comment]
- App is featured
- Description was changed to from "Whiteboard app" to "Create & collaborate on an infinite canvas!" as that shows presently in the app lists on the store, FYI @juliushaertl in case it needs adjustment in the info.xml or elsewhere. (Already updated the Github repo description)
- Past comments/ratings deleted cause they are unrelated to this new app as mentioned
